### ISSUE TITLE
Images not working on iOS

### ISSUE THREAD

**Issue by vgaraschuk** [ulangi/ulangi#102]
Images are not displayed on iOS. Tested on iPhone XR and iPad Pro (though they work fine on Android for the same account).
Steps to reproduce:
1) Press '+' to add a new card.
2) Write any definition.
3) Press 'extra fields' in the definition section.
4) Press 'Search images'.
5) Type anything in the search box (e.g. "cat").

Actual result: Grey boxes are displayed.
Expected result: Images are displayed.

Also grey boxes are displayed instead of images for already created cards.
Re-installing doesn't help.
![photo_2021-04-16_16-10-42](https://user-images.githubusercontent.com/82678814/115078921-5e735380-9ece-11eb-8746-b081a2e99825.jpg)
![photo_2021-04-16_16-10-38](https://user-images.githubusercontent.com/82678814/115078922-5f0bea00-9ece-11eb-893d-e77a6eb8bf37.jpg)

**Comment by minhloi** [comment]
I'm aware of this issue. This occurs when the app is compiled using the latest XCode version

**Comment by vgaraschuk** [comment]
Is there any way to fix it? I would attach the logs, but, it looks like all the logs are printed in the console. So the only way to debug it is to configure an iOS environment and attach it to XCode, which is quite problematic for me.
The application is great, and it beats anki in every way. I' don't know why so few people know about it. But it would be sad if its support got dropped.

**Comment by minhloi** [comment]
I will fix it soon.

**Comment by minhloi** [comment]
Should be fixed now in v3.21.1
