### ISSUE TITLE
App does not boot on Android 11

### ISSUE THREAD

**Issue by DaveDuck321** [ulangi/ulangi#103]
I have updated to Android 11 in the last few days. The app no longer boots past the initial splash screen and the spinner just spins indefinitely. This is an issue on both my phone and tablet and cannot be resolved by reinstalling the app. 

I have a reliable internet connection but this is also an issue if data is disabled. 

![Screenshot_20210426-005140](https://user-images.githubusercontent.com/30243291/116013774-cdb51a00-a629-11eb-83d7-dbae73e88923.jpg)

**Comment by MarinShalamanov** [comment]
Same problem for me on Android 12 DP.

**Comment by minhloi** [comment]
Looks like it only happens on Android 11 and above. I will look into this issue.

**Comment by jimmyloi** [comment]
Fixed in v3.21.1
