### ISSUE TITLE
Assembly problem

### ISSUE THREAD

**Issue by WildDuck46** [ulangi/ulangi#117]
I did everything according to the instructions, but this error always comes out
<img width="1080" alt="Снимок экрана 2021-09-06 в 02 06 56" src="https://user-images.githubusercontent.com/90155515/132139675-d7094bdc-e4bb-4f5d-8002-a6b64e3e6fd7.png">
<img width="1080" alt="Снимок экрана 2021-09-06 в 02 50 37" src="https://user-images.githubusercontent.com/90155515/132139739-eb9b33a5-cac4-4b14-975a-ed926fa5ec8d.png">

**Comment by WildDuck46** [comment]
Can you record a video of how to get it right?

**Comment by jimmyloi** [comment]
As the error message said, it failed at bcrypt install script. Check why it failed.

**Comment by jimmyloi** [comment]
https://www.npmjs.com/package/bcrypt

**Comment by WildDuck46** [comment]
Did not help. I have + bcrypt@5.0.1

**Comment by WildDuck46** [comment]
What is required for this application to work?

**Comment by WildDuck46** [comment]
Do you need to configure the server before launching the application or not?

**Comment by WildDuck46** [comment]
My problem is similar to this but I am using mac https://github.com/ulangi/ulangi/issues/77

**Comment by jimmyloi** [comment]
Check the npm log file. It shows you the exact reason why bcrypt failed and start from there. The link I posted is for you to look for the fix after you find the error. Or search google for the fix. I'm not the author of bcrypt so I cannot help you. Every system has different environment.

**Comment by WildDuck46** [comment]
The problem is solved by installing node version 10
