### ISSUE TITLE
opening the project with expo cli

### ISSUE THREAD

**Issue by eddybounasr** [ulangi/ulangi#72]
please can you help me open the project with expo cli?
i tried download the files >extract> npm install > expo start
but i am getting error that react native not installed in this project.
actully i want test the app on my phone and try edit the code.
for learning purposes.
![githubtoexpo](https://user-images.githubusercontent.com/23029177/80206288-b5847680-8634-11ea-986b-62c0f1e88050.PNG)

**Comment by minhloi** [comment]
Sorry I don't use Expo in this project. You don't think you need to use expo-cli to start it.
