### ISSUE TITLE
Spaced repetition order randomization

### ISSUE THREAD

**Issue by DaveDuck321** [ulangi/ulangi#78]
Currently all terms in both the Spaced Repetition modes appear in predictable orders. This is sometimes undesirable, for example when reviewing sets such as numbers, it is difficult to test recall when the terms will always appear in ascending order.

An option in either the category settings or the Spaced Repetition settings to randomize the review order would be appreciated.

**Comment by minhloi** [comment]
@DaveDuck321 Thanks. Added to-do list. This is easy to do but I don't know if there is any performance impact because we have to use ORDER BY RANDOM() to shuffle the database.

**Comment by minhloi** [comment]
9f848976945d02d1a09e7196def34be8477ce67c: Randomize review
